[workspace]
members = ["ctl", "daemon", "libmoxpaper"]
default-members = ["ctl", "daemon"]
resolver = "2"

[workspace.dependencies]
libmoxpaper = { path = "libmoxpaper" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
